server:
  servlet:
    context-path: /
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useSSL=false
    username: root
    password: 123456
#  profiles:
#    active: alpha

---
spring:
  profiles: alpha

db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jdbc?useSSL=false
  username: root
  password: 123456
